# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyleet < Formula
  desc "Lazygit-style terminal UI for practising on LeetCode"
  homepage "https://github.com/sven97/lazyleet"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sven97/lazyleet/releases/download/v0.1.0/lazyleet_0.1.0_darwin_amd64.tar.gz"
      sha256 "8afb860b3c7fb2d88d1b9bc5f79d21597f33276f080710538231abe17c150396"

      define_method(:install) do
        bin.install "lazyleet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sven97/lazyleet/releases/download/v0.1.0/lazyleet_0.1.0_darwin_arm64.tar.gz"
      sha256 "e238ef37993977f6325e781483dbd337a20bbcf14a66cd2f2496ee001f3df7fd"

      define_method(:install) do
        bin.install "lazyleet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sven97/lazyleet/releases/download/v0.1.0/lazyleet_0.1.0_linux_amd64.tar.gz"
      sha256 "883ab92697e76bc2567a41f23bf790f5ddb30f21d1963cb9341fa55b933273a0"
      define_method(:install) do
        bin.install "lazyleet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sven97/lazyleet/releases/download/v0.1.0/lazyleet_0.1.0_linux_arm64.tar.gz"
      sha256 "b64c1b674e0990946b6694d1a89a9e11131330af3144aae4008b9b3f2ad81d53"
      define_method(:install) do
        bin.install "lazyleet"
      end
    end
  end

  test do
    system "#{bin}/lazyleet", "--version"
  end
end
