# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyleet < Formula
  desc "Lazygit-style terminal UI for practising on LeetCode"
  homepage "https://github.com/sven97/lazyleet"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sven97/lazyleet/releases/download/v0.1.1/lazyleet_0.1.1_darwin_amd64.tar.gz"
      sha256 "f885e50f40ca87ce1aad25700dd223cb5c118003e1d7f3a0af42472f596b409a"

      define_method(:install) do
        bin.install "lazyleet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sven97/lazyleet/releases/download/v0.1.1/lazyleet_0.1.1_darwin_arm64.tar.gz"
      sha256 "96ecc4020095a8660bb37b7ddb6e52990d94876651dd3e4298cace2b4b146b51"

      define_method(:install) do
        bin.install "lazyleet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sven97/lazyleet/releases/download/v0.1.1/lazyleet_0.1.1_linux_amd64.tar.gz"
      sha256 "aa7905c79b750c261c312c1dc92b24040d9ef18a79732ddb0defc4d226857f7c"
      define_method(:install) do
        bin.install "lazyleet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sven97/lazyleet/releases/download/v0.1.1/lazyleet_0.1.1_linux_arm64.tar.gz"
      sha256 "a8d0b59d3d55d5080beb0d10b91e40d91702313bfa066734a1f566c866c8ca32"
      define_method(:install) do
        bin.install "lazyleet"
      end
    end
  end

  test do
    system "#{bin}/lazyleet", "--version"
  end
end
