# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyleet < Formula
  desc "Practice LeetCode in the terminal, in your own editor"
  homepage "https://github.com/sven97/lazyleet"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sven97/lazyleet/releases/download/v0.3.0/lazyleet_0.3.0_darwin_amd64.tar.gz"
      sha256 "01042097ad9e7492ea3e6e8488f9d90ddebb0967a5a138f4931069f33e6e0759"

      define_method(:install) do
        bin.install "lazyleet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sven97/lazyleet/releases/download/v0.3.0/lazyleet_0.3.0_darwin_arm64.tar.gz"
      sha256 "76d24940de88bce84bff552e3732609248db00032db6d72f2363ce6d9a2c3708"

      define_method(:install) do
        bin.install "lazyleet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sven97/lazyleet/releases/download/v0.3.0/lazyleet_0.3.0_linux_amd64.tar.gz"
      sha256 "875ac4c65e3eae5837d72f23de48307310ac9b8923063cc712cbc93f28d50f5a"
      define_method(:install) do
        bin.install "lazyleet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sven97/lazyleet/releases/download/v0.3.0/lazyleet_0.3.0_linux_arm64.tar.gz"
      sha256 "90ce4e17c7ded7c11be6c7980b17575f36d4fcef73ce09f097eb0ce4da172432"
      define_method(:install) do
        bin.install "lazyleet"
      end
    end
  end

  test do
    system "#{bin}/lazyleet", "--version"
  end
end
